version: '3.4'

services:
  estate-cost.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;
      - CONNECTION_STRINGS__DEFAULTCONNECTION=Host=87.242.93.11;Username=dev;Password=dev;Database=estate-cost;
      - AUTHORITY_URL=estate-cost.identity-server
    ports:
      - 5001:5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  estate-cost.identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001;
      - CONNECTION_STRINGS__DEFAULTCONNECTION=Host=87.242.93.11;Username=dev;Password=dev;Database=estate-cost;
    ports:
      - 6001:6001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  estate-cost.web.bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:4001;
      - AUTHORITY_URL=https://localhost:6001
      - API_URL=https://localhost:5001
    ports:
      - 4001:4001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
