version: '3.4'

services:
  estate-cost.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - CONNECTION_STRINGS__DEFAULTCONNECTION=Host=estate-cost.db.main;Username=dev;Password=dev;Database=estate-cost;
      - AUTHORITY_URL=estate-cost.identity-server
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  estate-cost.identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:6001;http://+:6000
      - CONNECTION_STRINGS__DEFAULTCONNECTION=Host=estate-cost.db.main;Username=dev;Password=dev;Database=estate-cost;
    ports:
      - 6000:6000
      - 6001:6001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  estate-cost.web.bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - AUTHORITY_URL=estate-cost.identity-server
      - API_URL=estate-cost.web.api/api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  estate-cost.db.main:
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: estate-cost
    ports:
      - 5432:5432